id = "zuzu"
name = "ZuzuScript"
version = "0.0.1"
schema_version = 1
authors = ["ZuzuScript contributors"]
description = "ZuzuScript language support for Zed"
repository = "https://github.com/zuzuscript/zed-zuzu"

[grammars.zuzu]
repository = "file:///home/tai/src/zuzuscript/tree-sitter-zuzu"
rev = "12dfe12157d6cdfc019457a2f9503a6a5dd75be3"
