id = "zuzu"
name = "ZuzuScript"
version = "0.0.1"
schema_version = 1
authors = ["ZuzuScript contributors"]
description = "ZuzuScript language support for Zed"
repository = "https://github.com/zuzuscript/zed-zuzu"

[grammars.zuzu]
repository = "file:///home/tai/src/zuzuscript/tree-sitter-zuzu"
rev = "98d3d64927d58894b6aca6cf69bdaa0892408f23"
