id = "zuzu"
name = "ZuzuScript"
version = "0.0.1"
schema_version = 1
authors = ["ZuzuScript contributors"]
description = "ZuzuScript language support for Zed"
repository = "https://github.com/zuzuscript/zed-zuzu"
languages = ["languages/zuzu"]
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.zuzu]
repository = "https://github.com/zuzuscript/tree-sitter-zuzu"
rev = "8593148756686092d0ac547ae868fca5d1b604a3"

[language_servers.zuzu-lsp]
name = "Zuzu LSP"
languages = ["ZuzuScript"]

[language_servers.zuzu-lsp.language_ids]
ZuzuScript = "zuzu"
